### ISSUE TITLE
Images truncated when using "mono" cga

### ISSUE THREAD

**Issue by VasylSamoilov** [jhpyle/mTCP#2]
I use following settings
SPECIAL=none
COLOR=mono
CGA=true
STRETCH=true

If there is some "clear" space in the top of the picture, it will be skipped. Whatever image vertical size it is, it will always stick to the top of the screen. Only affects "mono", 4 color cga is not affected.

**Comment by jhpyle** [comment]
Because of the aspect ratio of your screen (which is different from most CGA monitors), I think you should use `--nostretch`.  Does that change things?

**Comment by VasylSamoilov** [comment]
--nostretch disable stretch, but truncation is still there.
there is nothing special about this screen, it's CGA with strange pixel aspect ratio.
test files:
(1)
![2](https://user-images.githubusercontent.com/20946668/83771689-38b0d780-a68b-11ea-9377-dbcfe7e21ef2.png)
(2)
![1](https://user-images.githubusercontent.com/20946668/83771694-39496e00-a68b-11ea-91dc-72746579ccd4.png)
result:
(1)
![image](https://user-images.githubusercontent.com/20946668/83771738-46665d00-a68b-11ea-9064-c390f7ae3880.png)
(2)
![image](https://user-images.githubusercontent.com/20946668/83771767-4e260180-a68b-11ea-859d-e077d882f4cf.png)

**Comment by jhpyle** [comment]
That's very odd because I don't have any code capable of trimming whitespace from an image.

When I display those image files using `TELNET_CGA 1`, it looks like this:

![image](https://user-images.githubusercontent.com/11341940/83791824-3d17c900-a668-11ea-96b8-bd95c9ecf9d9.png)
![image](https://user-images.githubusercontent.com/11341940/83791876-4f920280-a668-11ea-8b1a-2aedfdaeeae4.png)
![image](https://user-images.githubusercontent.com/11341940/83791936-62a4d280-a668-11ea-94a5-f58c74314931.png)

The only way I could imagine that images would be trimmed is if you are running a different version of img2sixel that is trimming images.

When I run `img2sixel --version`, I get the following.
```
jpyle@pi:~ $ img2sixel --version
img2sixel 1.8.2

configured with:
  libcurl: no
  libpng: no
  libjpeg: no
  gdk-pixbuf2: no
  GD: no

Copyright (C) 2014-2018 Hayaki Saito <saitoha@me.com>.
```
Is this the same as what you get?

**Comment by VasylSamoilov** [comment]
probably you are right.
pi@raspberrypi:~ $ img2sixel --version
img2sixel 1.5.0
Copyright (C) 2014,2015 Hayaki Saito <saitoha@me.com>.

**Comment by jhpyle** [comment]
I tried installing libsixel version 1.5.0, and it doesn't truncate images for me.  So I don't know what's causing the truncation.
