### ISSUE TITLE
Feature request: EGA support

### ISSUE THREAD

**Issue by ajrossnz** [jhpyle/mTCP#4]
Having a period correct machine (an IBM PC XT/286 - 5162), I have an EGA display. It would be great to use sixel graphics with up to 16 colours rather than the 2 colour CGA mode. Is there any way of supporting EGA in the future?
Thanks!

**Comment by jhpyle** [comment]
You could probably use the 4-color CGA mode, not that it will be much better than 2 color.

Anyway, I would love to add EGA support but the problem is I don't have an EGA card or monitor, so I couldn't test it. I only have access to Hercules and MCGA. I would either need to buy the equipment (which is pretty expensive as far as I can tell from eBay) or get temporary access to a computer that has both EGA and ethernet. mTCP doesn't work in an emulator, at least any that I have found.

**Comment by ajrossnz** [comment]
Thanks. Well, I guess I'm willing to be a guinea pig for EGA if you want to send me some code or palette suggestions, but yeah I forgot that mTCP doesn't work (well) in an emulator.
